### ISSUE TITLE
Wallet to track

### ISSUE THREAD

**Issue by thealexcons** [iSyqozz/pump.fun-sniper#1]
Firstly, thanks for making this public :) I haven't tested it yet but will tip if I make profits.
I was just wondering what the input wallet to track represents? Could you please give an example? Is it the wallet of the person who deploys the pumpfun token?

Thanks

**Comment by thealexcons** [comment]
Also, what's the reasoning for adding an instruction for the memo program? Is it a way to land more transactions?

**Comment by iSyqozz** [comment]
```Wallet To Track``` represents the Dev wallet or address that is associated with a bonding curve launch aka 'pool launch'.

**Comment by skatekowski** [comment]
Hi, for me also thanks for making this public. That means it snipes tokens right at the launch on Raydium? Or can I somehow track wallets they buy on pump.fun? and copy their trades even before theiy reached the Bonding curve?

**Comment by iSyqozz** [comment]
This is a pump.fun sniper and not raydium.
If you are interested in a copy-trading bot.
Dm me on telegram or twitter and I can costum build one. As Im currently
working on one for a couple clients.

**Comment by skatekowski** [comment]
Yeah, I know it is pump.fun. But It would be more interesting copytrading wallets on pump.fun because when the bonding curve is reached and liquiditiy is added to raydium the sellers dump the price
